#ifndef DEMOCHARTS_HDR
#define DEMOCHARTS_HDR
#include "chartdir.h"
#include "FinanceChart.h"
#include "ADefineQ.h"
#include <vector>
using namespace std;
//////////////////////////////////////////////////////////////////////////////////
//
//	This demo program contains a number of demo chart functions. Each function 
//	can produce a number of demo charts. We store all the functions and their
//	descriptions into an array to facilitate processing
//
//////////////////////////////////////////////////////////////////////////////////

//  Forward declaration - represents a ChartDirector chart 
class BaseChart;

//	Structure representing a single demo chart function
struct DemoChart
{
	const char *name;	//name of the demo function
	int noOfCharts;		//the number of charts generated by this demo function
	BaseChart* (*createChart)(int chartNo, const char **imageMap);	//the demo function entry point
  //  const char *icon;   //icon for the demo
};

//	An array storing all demo chart functions. An empty entry signals the end 
//	of the array. 
extern DemoChart demoCharts[];


//qy modify the function
struct MaterialChart
{
    const char *name;
    int noOfCharts;
    //BaseChart* (*createChart)(StringArray dataX, DoubleArray dataY, const char **imageMap);
    BaseChart* (*createChart)(StringArray dataX, vector<DoubleArray> dataY, const char **imageMap);
    BaseChart* (*propChart)(StringArray dataX, vector<DoubleArray> dataY, const char **imageMap, _WELCME_CHART_PROP_ propCh);
  //  const char *icon;   //icon for the demo
};

struct unEVENChart
{
    const char *name;
    int noOfCharts;
    //BaseChart* (*createChart)(StringArray dataX, DoubleArray dataY, const char **imageMap);
    BaseChart* (*createChart)(vector<DoubleArray>  dataX, vector<DoubleArray> dataY, const char **imageMap, _WELCME_CHART_PROP_ propCh);
  //  const char *icon;   //icon for the demo
};

extern MaterialChart materialCharts[];
extern unEVENChart unEvenChart[];

enum _COLOR_ENUM_{
   /* COLOR_ENUM_BLUE1 =1,
    COLOR_ENUM_YELLOW1=11,
    COLOR_ENUM_GREEN1=21,*/
    COLOR_ENUM_BLUE1 =1,
    COLOR_ENUM_YELLOW1=2,
    COLOR_ENUM_GREEN1=3,
};
struct _WELCMN_COLOR_{
   
    unsigned long int wls_clr[100];
    _WELCMN_COLOR_(){
        wls_clr[0] = 0x5588cc;//蓝色
        wls_clr[1] = 0xee9944;//黄色
        wls_clr[2] = 0x99bb55;//绿色
        wls_clr[3] = 0xff80ff;//红色()


        wls_clr[4] = 0x0000ff;//蓝色
        wls_clr[5] = 0xff0000;//黄色
        wls_clr[6] = 0x00ff00;//绿色
      
       //wls_clr[1] = 0x0000ff;//blue
       //wls_clr[2] = 0x5588cc;

       //wls_clr[12] = 0xff0000;//red
       //wls_clr[12] = 0xee9944;//黄色

       //wls_clr[21] = 0x00ff00;//green
       //wls_clr[22] = 0x99bb55;
    }

};

#endif
